# 使用方式：
# 手动在本地运行 pre-commit
# pre-commit run --all-files
# 远程 CI 运行只会检查，不会修改代码

repos:
  # Generic
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict # Check for files with names that would conflict on a case-insensitive filesystem like MacOS HFS+ or Windows FAT.
      - id: check-docstring-first # Checks for a common error of placing code before the docstring.
      - id: check-executables-have-shebangs # Checks that non-binary executables have a proper shebang.
      - id: check-json # Attempts to load all json files to verify syntax.
      - id: check-shebang-scripts-are-executable # Checks that scripts with shebangs are executable.
      - id: check-symlinks # Checks for symlinks which do not point to anything.
      - id: check-toml # Attempts to load all TOML files to verify syntax.
      - id: check-yaml # Attempts to load all yaml files to verify syntax.
      - id: trailing-whitespace # Trims trailing whitespace.
      - id: end-of-file-fixer # Makes sure files end in a newline and only a newline.
      - id: check-added-large-files # Prevent giant files from being committed.
